name: blockchain_wallet
description: "区块链钱包APP"
publish_to: 'none'
version: 1.0.0+1

environment:
#  sdk: ^3.7.2
   sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.10
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0
  equatable: ^2.0.7
  go_router: ^14.8.1
  wallet_core_bindings: ^4.2.18
  wallet_core_bindings_native: ^4.2.18
  wallet_core_bindings_libs: ^4.2.18
  logger: ^2.5.0
  get_it: ^8.0.3
  biometric_storage: ^5.0.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.12
  pointycastle: ^4.0.0 #加密算法库
  hex: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.4

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
  class_name: "S"        # 生成的国际化类名（默认 AppLocalizations）
  main_locale: "zh_CN"       # 默认语言（如 en、zh）
  use_cupertino: false    # 是否生成 Cupertino 支持
  arb_dir: "lib/l10n"     # ARB 文件目录
  output_dir: "lib/generated" # 生成代码目录
